### ISSUE TITLE
[FEAT] Add login component

### ISSUE THREAD

**Issue by Rostislav013** [MikeVedsted/JoinMe#85]
**💡 I would really like to solve or include**   
Clearly and concisely describe the problem you are trying to solve.   

Currently there is a button to login, but its located anyhow.
Need to find a place for login button.

**👶 How would a user describe this?**   
Describe how users are affected by statements users might make or a user story.  

Where is the button, Lebowski?
  
**🏆 My dream solution would be**  
Describe the best possible scenario of this being implemented.  

After clicking on login button I am logged in LOL

**:2nd_place_medal: But I'd also consider it solved if**    
Describe an implementation that would fulfill the basic wish but might need more work in the future.  

One of the way, in navbar change current `h` tag Login to this login button.

**💭 If you were doing it, what would you do?**   
If possible, describe the steps you would take to implement this.   

*Ex. I would add a functionality that remembers the events that have been viewed by an individual user*   
*1. add an array to the user profile of events they have views*   
*2. check against the array before displaying an event*    

**♻️ Additional context**  
Describe any other reasons that might make this feature necessary.  

*Ex. BigCompetitor has this function and users are switching to them for this reason.*    
*Ex. We have to implement this to comply with SomeLegalStandard.*    
*Ex. MarketingTeam is unable to perform ABX until ABZ has been enabled, costing them 1 billion nanodullar per day 💰*

**🚀 I'm ready for take off**  
Before submitting, please mark if you:  
- [ ] Checked that this feature doesn't already exists  
- [ ] Checked that a feature request doesn't already exists  
- [ ] Went through the user flow, and understand the impact  
- [ ] Made sure the request shows why it is important to users but doesn't exaggerate the value

**Comment by MikeVedsted** [comment]
@Rostislav013 I think this issue is no longer relevant.

**Comment by Rostislav013** [comment]
closing due its a part for dropdown menu
