### ISSUE TITLE
[FEAT] Add user authentication

### ISSUE THREAD

**Issue by MikeVedsted** [MikeVedsted/JoinMe#9]

**Comment by nannadao** [comment]
💡 I would really like to solve or include
It should be able for user to login/ create account using Google Login.

👶 How would a user describe this?
I would like to create an account using my Google account. For next visits, I would like my information and events to persist.

🏆 My dream solution would be
User is able to login/ create new account with Google. 

🥈 But I'd also consider it solved if
N/A

💭 If you were doing it, what would you do?
1. Create google callback route
2. Find existing user/ create new user 
3. Assign token to user
4. Return authenticated user + token

♻️ Additional context
N/A

🚀 I'm ready for take off
Before submitting, please mark if you:

[x] Checked that this feature doesn't already exists
[x] Checked that a feature request doesn't already exists
[x] Went through the user flow, and understand the impact
[x] Made sure the request shows why it is important to users but doesn't exaggerates the value

**Comment by MikeVedsted** [comment]
#38 merged
